### ISSUE TITLE
Process didn't exit successfully

### ISSUE THREAD

**Issue by tangdaoyuan** [sindresorhus/win-wallpaper#10]
### Description
![image](https://user-images.githubusercontent.com/8007202/223444922-67d562b7-7dc8-48c7-8801-3164b1db6a3a.png)

rustc 1.67.1 (d5a82bbd2 2023-02-07)
Microsoft Windows 10.0.19044.2604

### Reproduction
* just clone and cargo run get 

### Try
Try to comment out the following code, then cargo run works
https://github.com/sindresorhus/win-wallpaper/blob/b55c6f6c20d629627d215d43836f9e8eed2547c2/src/lib.rs#L142

I am not good at Rust or C++,  so I try to fix this by the [post](https://devblogs.microsoft.com/oldnewthing/20040520-00/?p=39243).

**Comment by sindresorhus** [comment]
// @a-isaiahharvey
