### ISSUE TITLE
Use return, not exit()

### ISSUE THREAD

**Issue by Qix-** [sindresorhus/win-wallpaper#2]
Even though it's pretty innocuous in this program, try to use `return 0;` instead of `exit(0);` when in the main function.

**Comment by sindresorhus** [comment]
What's the reasoning? From my noobish view they do exactly the same?

**Comment by Qix-** [comment]
`return` allows the program to clean up its resources. `exit()` does not (it never returns).

**Comment by arthurvr** [comment]
Yeah, I prefer `return` too.
