### ISSUE TITLE
Failed to set the desktop wallpaper in W7

### ISSUE THREAD

**Issue by leonetosoft** [sindresorhus/win-wallpaper#4]
Hello good afternoon,

Congratulations on your work, it works perfectly on windows 10 but on windows 7 I have this message:

"**Failed to set the desktop wallpaper**"

**Comment by phanirithvij** [comment]
I thinks it's meant for Windows 10+ as mentioned here.

https://github.com/sindresorhus/wallpaper/blob/master/readme.md

The same `win-wallpaper` is the one that's being used in it and is written by the sindresorhus (same guy)
